"""first

Revision ID: 0b1add0c6f9b
Revises: ee05e1a5704d
Create Date: 2022-08-22 09:34:17.568272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1add0c6f9b'
down_revision = 'ee05e1a5704d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
