"""third

Revision ID: fbe63ab0ed7d
Revises: 4a11e4582162
Create Date: 2022-08-24 10:01:11.461385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe63ab0ed7d'
down_revision = '4a11e4582162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
