# File for manual testing api server, install rest client extension in vscode

POST http://0.0.0.0:5000/users/create
Content-Type: application/json

{
    "username": "parth3",
    "password": "abc",
    "is_student": false,
    "email": "abc@gmail.com"
}

###
GET http://0.0.0.0:5000/users?limit=2
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicGFydGgzIiwiZW1haWwiOiJhYmNAZ21haWwuY29tIiwiaXNfc3R1ZGVudCI6ZmFsc2UsImV4cCI6MTY2MDM1NjUyNn0.3VXAnQC7ZKp2vgdYCf9jb_cmvA_T_EiU8VBqkq6wE4U
###
GET http://0.0.0.0:5000/environment/parth3
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicGFydGgzIiwiZW1haWwiOiJhYmNAZ21haWwuY29tIiwiaXNfc3R1ZGVudCI6ZmFsc2UsImV4cCI6MTY2MDM1NjUyNn0.3VXAnQC7ZKp2vgdYCf9jb_cmvA_T_EiU8VBqkq6wE4U

###
POST http://0.0.0.0:5000/webapp/logout?username=gg
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicGFydGgzIiwiZW1haWwiOiJhYmNAZ21haWwuY29tIiwiaXNfc3R1ZGVudCI6ZmFsc2UsImV4cCI6MTY2MDM1Njk2M30.oE_An-3kmAmSWQ8l2TmNHfR5OULSlCEYjht5r-XscR4

###
POST http://0.0.0.0:5000/webapp/login
Content-Type: application/json

{
    "username": "parth1",
    "password": "abc3"
}