POST http://0.0.0.0:5000/create-user
Content-Type: application/json

{
    "username": "parth2",
    "password": "abc",
    "is_student": true,
    "email": "abc2@gmail.com"
}

###
GET http://0.0.0.0:5000/students?limit=1

###
GET http://0.0.0.0:5000/getenv?username=parth1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicGFydGgxIiwiZW1haWwiOiJhYmMxQGdtYWlsLmNvbSIsImlzX3N0dWRlbnQiOnRydWUsImV4cCI6MTY1OTk4MTY3MX0.ov4HYx7uVtX6RzGIQtO4wG4tO1Hfsd8cpTew0Pvi3Z4

###
POST http://0.0.0.0:5000/logout?username=parth1
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicGFydGgxIiwiZW1haWwiOiJhYmMxQGdtYWlsLmNvbSIsImlzX3N0dWRlbnQiOnRydWUsImV4cCI6MTY2MDAzODA4Mn0.QrdUvza0TwImX_liNYDTg5CRXe-aXOdIQTbucgGeeK0

###
POST http://0.0.0.0:5000/login
Content-Type: application/json

{
    "username": "parth1",
    "password": "abc"
}