"""First

Revision ID: ee05e1a5704d
Revises: 
Create Date: 2022-08-19 01:39:09.709667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee05e1a5704d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user', sa.String(), nullable=True))
    op.create_foreign_key(None, 'refresh_tokens', 'user', ['user'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'user')
    # ### end Alembic commands ###
